docs: add lambda endpoints usage documentation
linz/geospatial-data-lake pull request #212
Opened 2021-02-01 13:49 UTC by imincik

2021-02-01 19:01 UTC, l0b0 requested changes

2021-02-01 19:01 UTC, l0b0 commented on USAGE.md
> +$ export DATALAKE_LAMBDA_FUNCTION_ENDPOINT_NAME=<DATALAKE-LAMBDA-FUNCTION-ENDPOINT-NAME>
Do users need some instructions to retrieve the endpoint name? I'm not even completely sure I could get this command right.

2021-02-01 22:01 UTC, billgeo requested changes
Thanks @imincik looks more or less fine to me. I think adding a bit more info about how to get the endpoints and account IDs etc and it's good to go. I will try and test this this week, but please merge this when it's ready.

2021-02-02 16:59 UTC, imincik commented on USAGE.md
> +export DATALAKE_AWS_ACCOUNT_ID=<DATALAKE-AWS-ACCOUNT-ID>
I agree with Bill on this comment.

2021-02-02 17:30 UTC, imincik commented on USAGE.md
> +        --function-name datasets-endpoint \
For while yes, but we are talking about using AWS autogenerated resource names.

2021-02-02 17:39 UTC, imincik commented
@billgeo , @l0b0 thanks for your comments. I applied changes to all of them and also add "Prerequisites" section listing all information need in order to start using DL.

I'll merge this PR now

2021-02-02 17:39 UTC, merged