docs: missing summary of import status end point
linz/geospatial-data-lake pull request #471
Opened 2021-03-28 23:21 UTC by billgeo

## Issues

Noticed a summary of the import status endpoint was missing in the usage docs

## Challenges

- [X doesn't support Y](https://example.org/issues/1)

## Reference

[Code review checklist](CODING.md#Code-review-checklist)

2021-03-28 23:41 UTC, l0b0 requested changes

2021-03-28 23:41 UTC, l0b0 commented on USAGE.md
> +- A [import status endpoint](TODO), to get information about the status of dataset version import, including errors and issues
"A" should be "An"

2021-03-29 01:29 UTC, billgeo commented on USAGE.md
> +- A [import status endpoint](TODO), to get information about the status of dataset version import, including errors and issues
Done

2021-03-29 01:50 UTC, l0b0 approved these changes

2021-03-29 03:14 UTC, merged