ci: wait if another CI AWS stack already exists
linz/geospatial-data-lake pull request #61
Opened 2020-11-16 11:34 UTC by imincik

To prevent AWS resource names conflicts.

2020-12-01 22:56 UTC, imincik commented on .github/workflows/ci.yml
> +                  while [[ -n "${e}" ]]; do echo "Waiting for ${s} teardown ..."; sleep 3; done
I have empty output. Which version of AWS CLI do you use ?

Mine is 

```
aws --version
aws-cli/1.18.185 Python/3.6.9 Linux/4.15.0-122-generic botocore/1.19.26

```

2020-12-01 23:10 UTC, l0b0 commented on .github/workflows/ci.yml
> +                  while [[ -n "${e}" ]]; do echo "Waiting for ${s} teardown ..."; sleep 3; done
How weird, on my new laptop I get an empty response as well:

```
$ aws --version
aws-cli/1.18.173 Python/3.8.6 Linux/5.9.11-arch2-1 botocore/1.19.13
```

2020-12-01 23:10 UTC, l0b0 approved these changes

2020-12-02 14:31 UTC, imincik commented on .github/workflows/ci.yml
> +                  while [[ -n "${e}" ]]; do echo "Waiting for ${s} teardown ..."; sleep 3; done
Maybe your old laptop used version 2 of AWS CLI ?

2020-12-02 22:06 UTC, l0b0 commented on .github/workflows/ci.yml
> +                  while [[ -n "${e}" ]]; do echo "Waiting for ${s} teardown ..."; sleep 3; done
Oh, doesn't matter. You can ignore that part of the comment, but the global timeout issue still stands.

2020-12-03 03:32 UTC, l0b0 requested changes
As mentioned, there should be a global timeout to avoid CI running forever.

2020-12-07 19:55 UTC, l0b0 approved these changes

2020-12-07 19:56 UTC, merged