feat: Add Koordinates storage access role
linz/geospatial-data-lake pull request #617
Opened 2021-04-22 03:11 UTC by l0b0

## Issues

Related to https://github.com/linz/geospatial-data-lake/issues/496.

## Reference

[Code review checklist](CODING.md#Code-review-checklist)

2021-04-22 04:23 UTC, imincik requested changes
Please move koordinates role to separare `lds_stack.py` which can be optionally enabled for deployment when env variable `ENABLE_LDS_ACCESS` is set to yes or true. This will help with reusability of our software for others (others wouldn't need to allow LDS access)

2021-04-26 21:43 UTC, l0b0 commented
> Please move koordinates role to separare `lds_stack.py` which can be optionally enabled for deployment when env variable `ENABLE_LDS_ACCESS` is set to yes or true. This will help with reusability of our software for others (others wouldn't need to allow LDS access)

I've elected to make this part of the CDK context, which should be easier to modify than dealing with environment variables.

2021-04-27 04:56 UTC, imincik submitted a review, later dismissed

2021-04-28 03:35 UTC, imincik approved these changes

2021-04-28 03:35 UTC, merged